name: Challenge Reward System

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  validate-challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Validate challenge solution
        run: |
          python .github/scripts/validate_key.py
          
      - name: Award key if solution is correct
        if: success()
        run: |
          python .github/scripts/award_key.py
          
      - name: Unlock next lesson
        if: success()
        run: |
          python .github/scripts/unlock_lesson.py
